const KEYWORDS={
'Броня':'Поглощает физический урон и обычно исчезает между раундами.','Оберег':'Магическая защита от заклинаний и проклятий.','Резонанс':'Общий ресурс для командных приёмов. Возникает от совпадающих тегов карт.','Яд':'Наносит урон в конце раунда, затем обычно уменьшается на 1.','Кровотечение':'Наносит периодический физический урон.','Рок':'Не уменьшается и наносит урон в конце раунда.','Слабость':'Уменьшает урон атак противника.','Уязвимость':'Увеличивает получаемый целью урон.','Истощение':'Карта отправляется в Пепел и не возвращается в этом бою.','Слуга':'Призванное существо, атакующее в конце раунда.','Передний ряд':'Приоритетная цель ближних атак. Усиливает оружие.','Задний ряд':'Безопаснее от ближних атак, но уязвим для рывков и дальних атак.','Быстрая':'Карта с высоким приоритетом разрешения.','Тяжёлая':'Мощная карта, обычно дорогая и медленная.','Реакция':'Защитный ответ на действие противника.','Благословение':'Положительный модификатор комнаты или боя.','Проклятие':'Опасный модификатор, обычно увеличивающий награду.'};
let LOG_FILTER='all';
const _richCache=new Map();
function richCardText(text){let cached=_richCache.get(text);if(cached!==undefined)return cached;let out=text;Object.keys(KEYWORDS).sort((a,b)=>b.length-a.length).forEach(k=>{out=out.replace(new RegExp(`(${k})`,'gi'),m=>`<span class="keyword" title="${KEYWORDS[k]}">${m}</span>`)});_richCache.set(text,out);return out}
function showGlossary(){openModal(`<div class="eyebrow">Справочник</div><h2>Ключевые понятия</h2><p class="modal-sub">Термины в описаниях карт подчёркнуты. Наведите на них для быстрой подсказки.</p><div class="glossary-grid">${Object.entries(KEYWORDS).map(([k,v])=>`<div class="glossary-item"><b>${k}</b><div class="small">${v}</div></div>`).join('')}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">Закрыть</button></div>`)}
function renderCombatLog(){let box=$('#combatLog');if(!box||!B)return;let rows=(B.log||[]).map(x=>typeof x==='string'?{text:x,cat:'system'}:x).filter(x=>LOG_FILTER==='all'||x.cat===LOG_FILTER).slice(-7);box.innerHTML=rows.map(x=>`<div class="log-entry ${['damage','status','system'].includes(x.cat)?x.cat:'system'}">${esc(x.text)}</div>`).join('');box.scrollTop=box.scrollHeight}
function setLogFilter(f,btn){LOG_FILTER=f;$$('.log-toolbar button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderCombatLog()}
function estimateCard(id){if(!B)return'';let c=getCard(id),h=G.heroes[B.active],d=c.dmg||0;if(c.blockStrike)d=Math.floor(h.block*c.blockStrike);if(c.command)d=h.minions*(h.minionPower+skillStat(h,'minion'));if(c.sacrificeAll)d=h.minions*7;if(d){d+=h.strength+skillStat(h,'damage')+(h.nextAttack||0);let hits=c.hits||1;if(c.bleedExecute&&B.enemy.bleed>=8)d*=c.bleedExecute;let blocked=Math.min(B.enemy.block,d*hits),actual=Math.max(0,d*hits-blocked);return `Прогноз: ≈ ${actual} урона${blocked?' · '+blocked+' заблокировано':''}`}if(c.block||c.allBlock)return `Прогноз: +${c.block||c.allBlock} брони`;if(c.heal)return `Прогноз: +${c.heal} здоровья`;return (c.tags||[]).join(' · ')}
function previewCard(id,el){if(!B||!el||$('#battle').classList.contains('hidden'))return;let c=getCard(id),enemy=$('#enemyUI'),text=estimateCard(id),ui=$('#previewUI');if(ui)ui.textContent=text;if(c.type==='attack'||c.command||c.sacrificeAll){enemy?.classList.add('preview-target');let a=el.getBoundingClientRect(),b=enemy.getBoundingClientRect(),x=a.left+a.width/2,y=a.top+20,x2=b.left+b.width/2,y2=b.top+b.height/2,l=Math.hypot(x2-x,y2-y),ang=Math.atan2(y2-y,x2-x)*180/Math.PI,line=document.createElement('i');line.className='target-line';line.id='targetLine';line.style.cssText=`left:${x}px;top:${y}px;width:${l}px;transform:rotate(${ang}deg)`;document.body.append(line)}let tip=document.createElement('div');tip.id='cardPreview';tip.className='card-preview';tip.textContent=text;let r=el.getBoundingClientRect();tip.style.left=Math.max(8,r.left)+'px';tip.style.top=Math.max(62,r.top-35)+'px';document.body.append(tip)}
function clearCardPreview(){$('#targetLine')?.remove();$('#cardPreview')?.remove();$('#enemyUI')?.classList.remove('preview-target');let ui=$('#previewUI');if(ui)ui.textContent=''}
const SETTINGS=Object.assign({master:.8,music:.42,sfx:.75,font:100,motion:100},(()=>{try{return JSON.parse(localStorage.getItem('ashspire-settings'))||{}}catch(e){return{}}})());
let AUDIO={ctx:null,master:null,music:null,sfx:null,drone:[],timer:null,started:false};
function initAudio(){if(AUDIO.ctx){if(AUDIO.ctx.state==='suspended')AUDIO.ctx.resume();return}let C=window.AudioContext||window.webkitAudioContext;if(!C)return;let c=AUDIO.ctx=new C();AUDIO.master=c.createGain();AUDIO.music=c.createGain();AUDIO.sfx=c.createGain();AUDIO.music.connect(AUDIO.master);AUDIO.sfx.connect(AUDIO.master);AUDIO.master.connect(c.destination);applyAudioSettings();startMusic()}
function applyAudioSettings(){if(!AUDIO.ctx)return;let t=AUDIO.ctx.currentTime;AUDIO.master.gain.setTargetAtTime(SETTINGS.master,t,.04);AUDIO.music.gain.setTargetAtTime(SETTINGS.music*.22,t,.08);AUDIO.sfx.gain.setTargetAtTime(SETTINGS.sfx*.35,t,.04)}
function startMusic(){if(AUDIO.started||!AUDIO.ctx)return;AUDIO.started=true;let c=AUDIO.ctx;[55,82.41,110].forEach((f,i)=>{let o=c.createOscillator(),g=c.createGain(),lp=c.createBiquadFilter();o.type=i===1?'triangle':'sine';o.frequency.value=f;lp.type='lowpass';lp.frequency.value=260;g.gain.value=i===0?.17:.07;o.connect(lp);lp.connect(g);g.connect(AUDIO.music);o.start();AUDIO.drone.push(o)});let notes=[220,246.94,293.66,329.63,246.94,196];let step=0;AUDIO.timer=setInterval(()=>{if(!AUDIO.ctx||AUDIO.ctx.state!=='running'||SETTINGS.music<=0)return;let now=AUDIO.ctx.currentTime,o=AUDIO.ctx.createOscillator(),g=AUDIO.ctx.createGain(),d=AUDIO.ctx.createDelay();o.type='sine';o.frequency.value=notes[step++%notes.length]/2;d.delayTime.value=.34;o.connect(g);g.connect(AUDIO.music);g.connect(d);d.connect(AUDIO.music);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.12,now+.12);g.gain.exponentialRampToValueAtTime(.001,now+2.8);o.start(now);o.stop(now+3)},3200)}
function tone(freq,dur=.12,type='sine',vol=.15,slide=0){if(!AUDIO.ctx)return;let c=AUDIO.ctx,now=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+dur);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(vol,now+.015);g.gain.exponentialRampToValueAtTime(.001,now+dur);o.connect(g);g.connect(AUDIO.sfx);o.start(now);o.stop(now+dur+.03)}
function noise(dur=.16,vol=.11){if(!AUDIO.ctx)return;let c=AUDIO.ctx,n=Math.floor(c.sampleRate*dur),b=c.createBuffer(1,n,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);let src=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();src.buffer=b;f.type='bandpass';f.frequency.value=900;g.gain.value=vol;src.connect(f);f.connect(g);g.connect(AUDIO.sfx);src.start()}
function playSfx(k){if(!AUDIO.ctx)return;switch(k){case'click':tone(520,.055,'sine',.045,-80);break;case'card':noise(.12,.08);tone(430,.12,'triangle',.08,180);break;case'attack':noise(.18,.16);tone(145,.17,'sawtooth',.13,-70);break;case'hurt':tone(95,.2,'square',.1,-40);break;case'heal':tone(440,.3,'sine',.09,220);setTimeout(()=>tone(660,.25,'sine',.07,180),90);break;case'battle':tone(110,.5,'sawtooth',.11,45);break;case'boss':tone(65,.8,'sawtooth',.16,-20);setTimeout(()=>tone(98,.7,'square',.1,-30),180);break;case'win':[392,523,659].forEach((n,i)=>setTimeout(()=>tone(n,.5,'sine',.11,40),i*130));break;case'shuffle':noise(.28,.09);tone(280,.16,'triangle',.05,160);break;case'error':tone(120,.12,'square',.08,-30)}}
function combatAnim(target){let el=$(target==='enemy'?'#enemyUI':'#battleParty');if(!el)return;el.classList.remove(target==='enemy'?'hit-shake':'hero-hit');void el.offsetWidth;el.classList.add(target==='enemy'?'hit-shake':'hero-hit');if(target==='enemy'){let fx=document.createElement('i');fx.className='slash-fx';fx.style.left='70%';fx.style.top='31%';$('.arena').appendChild(fx);setTimeout(()=>fx.remove(),450)}setTimeout(()=>el.classList.remove('hit-shake','hero-hit'),450)}
function openSettings(){let pct=x=>Math.round(x*100);openModal(`<div class="eyebrow">Параметры</div><h2>Настройки</h2><div class="modal-sub">Изменения применяются сразу и сохраняются в браузере.</div><div class="settings-grid"><div class="setting-row"><label>Общая громкость</label><input type="range" min="0" max="100" value="${pct(SETTINGS.master)}" oninput="changeSetting('master',this.value,this.nextElementSibling)"><output>${pct(SETTINGS.master)}%</output></div><div class="setting-row"><label>Музыка</label><input type="range" min="0" max="100" value="${pct(SETTINGS.music)}" oninput="changeSetting('music',this.value,this.nextElementSibling)"><output>${pct(SETTINGS.music)}%</output></div><div class="setting-row"><label>Эффекты</label><input type="range" min="0" max="100" value="${pct(SETTINGS.sfx)}" oninput="changeSetting('sfx',this.value,this.nextElementSibling)"><output>${pct(SETTINGS.sfx)}%</output></div><div class="setting-row"><label>Размер текста</label><input type="range" min="85" max="125" step="5" value="${SETTINGS.font}" oninput="changeSetting('font',this.value,this.nextElementSibling)"><output>${SETTINGS.font}%</output></div><div class="setting-row"><label>Скорость анимаций</label><input type="range" min="50" max="200" step="50" value="${SETTINGS.motion}" oninput="changeSetting('motion',this.value,this.nextElementSibling)"><output>${SETTINGS.motion}%</output></div></div><div class="modal-actions"><button class="btn primary" onclick="closeModal()">Готово</button><button class="btn" onclick="resetSettings()">Сбросить</button></div>`)}
function changeSetting(k,v,out){v=+v;SETTINGS[k]=(k==='font'||k==='motion')?v:v/100;out.textContent=v+'%';saveSettings()}
function saveSettings(){localStorage.setItem('ashspire-settings',JSON.stringify(SETTINGS));document.documentElement.style.setProperty('--fs',SETTINGS.font/100);document.body.classList.toggle('fast-motion',SETTINGS.motion>=150);document.body.classList.toggle('slow-motion',SETTINGS.motion<=50);applyAudioSettings()}
function resetSettings(){Object.assign(SETTINGS,{master:.8,music:.42,sfx:.75,font:100,motion:100});saveSettings();closeModal();openSettings()}
function restartRun(){if(!confirm('Завершить текущий забег и начать заново?'))return;if(G&&G.mode==='solo')soloSelect();else newRun()}
function leaveToMenu(){let inBattle=!$('#battle').classList.contains('hidden'),msg=inBattle&&G&&G.mode==='solo'?'Выйти в главное меню? Бой будет начат заново при продолжении забега.':'Выйти в главное меню? Текущий одиночный прогресс сохранится.';if(!confirm(msg))return;if(G&&!NET.active&&!inBattle)saveRun();if(NET.active&&NET.ref){NET.ref.child('state').off();NET.ref.child('actions').off();NET.ref.child('meta/guest').off();NET.ref.child('meta/guestOnline').off();NET.ref.off();if(NET.role==='guest')NET.ref.child('meta/guestOnline').set(false)}NET.active=false;NET.role=null;NET.room=null;NET.ref=null;B=null;G=null;hideAll();$('#menu').classList.remove('hidden');updateNetBadge();updateContinueButton();updateTop();playSfx('click')}
function updateContinueButton(){let b=$('#continueBtn');if(b)b.disabled=!localStorage.getItem('ashspire-save')}
document.addEventListener('pointerdown',e=>{initAudio();if(e.target.closest('button'))playSfx('click')},{passive:true});
saveSettings();
const continueBtn=$('#continueBtn');updateContinueButton();
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modalBack').classList.contains('hidden'))closeModal()});
